return PlaceObj('ModDef', {
	'title', "The Martian Tribune",
	'image', "Martian Tribune Preview Picture.png",
	'last_changes', "smaller preview image to reduce mod file size",
	'id', "lf1iELO",
	'steam_id', "1376913896",
	'author', "CheTranqui",
	'version', 775,
	'lua_revision', 233467,
	'code', {
		"Code/Initialization.lua",
		"Code/SaveGameFixes/MartianTribuneSaveGameFixes.lua",
		"Code/SaveGameFixes/775/1_SetStoryKeys.lua",
		"Code/SaveGameFixes/775/2_SetMissingPublishedDay.lua",
		"Code/SaveGameFixes/775/3_FixStoryChains.lua",
		"Code/SaveGameFixes/775/4_FixDomeDelayColonist.lua",
		"Code/SaveGameFixes/775/5_UpdateGlobals.lua",
		"Code/SaveGameFixes/775/Upgrade.lua",
		"Code/MartianTribune.lua",
		"Code/UI/Common.lua",
		"Code/UI/Notification.lua",
		"Code/UI/FrontPage.lua",
		"Code/UI/TopArchive.lua",
		"Code/UI/EngPage.lua",
		"Code/UI/EngArchive.lua",
		"Code/UI/SocialPage.lua",
		"Code/UI/SocialArchive.lua",
		"Code/Stories/InitialStoryLists.lua",
		"Code/Stories/Building/Arcology.lua",
		"Code/Stories/Building/ConcreteLove.lua",
		"Code/Stories/Building/Diner.lua",
		"Code/Stories/Building/Dome.lua",
		"Code/Stories/Building/DomeOval.lua",
		"Code/Stories/Building/Infirmary.lua",
		"Code/Stories/Building/MartianUniversity.lua",
		"Code/Stories/Building/MDSLaser.lua",
		"Code/Stories/Building/Moxie.lua",
		"Code/Stories/Building/OpenAirGym.lua",
		"Code/Stories/Building/PreciousMetalsExtractor.lua",
		"Code/Stories/Building/ShuttleHub.lua",
		"Code/Stories/Building/Spacebar.lua",
		"Code/Stories/Colonist/AdultFilm.lua",
		"Code/Stories/Colonist/ConcretePaving.lua",
		"Code/Stories/Colonist/DroneHack.lua",
		"Code/Stories/Colonist/DroneRights.lua",
		"Code/Stories/Colonist/EarthlingDomeDelay.lua",
		"Code/Stories/Colonist/EarthsickColonist.lua",
		"Code/Stories/Colonist/EarthTourism.lua",
		"Code/Stories/Colonist/FightClub.lua",
		"Code/Stories/Colonist/FirstFounderDied.lua",
		"Code/Stories/Colonist/FirstMartianbornDied.lua",
		"Code/Stories/Colonist/FoundersFirstWords.lua",
		"Code/Stories/Colonist/FoundersLegacy.lua",
		"Code/Stories/Colonist/FutureExpansion.lua",
		"Code/Stories/Colonist/GuruGarden.lua",
		"Code/Stories/Colonist/HappyBirthday.lua",
		"Code/Stories/Colonist/Hippie.lua",
		"Code/Stories/Colonist/IdiotFML.lua",
		"Code/Stories/Colonist/LeaderDied.lua",
		"Code/Stories/Colonist/MartianCelebrity.lua",
		"Code/Stories/Colonist/NewLeader.lua",
		"Code/Stories/Colonist/OopsIBrokeItAgain.lua",
		"Code/Stories/Colonist/PetRock.lua",
		"Code/Stories/Colonist/ReligiousArtifact.lua",
		"Code/Stories/Colonist/StarvingColonist.lua",
		"Code/Stories/Colonist/Vegan.lua",
		"Code/Stories/Colonist/VirtueOverVices.lua",
		"Code/Stories/Drone/DroneBreakdown.lua",
		"Code/Stories/Drone/DroneGoesViral.lua",
		"Code/Stories/Drone/DroneShortage.lua",
		"Code/Stories/General/CaptureTheFlag.lua",
		"Code/Stories/General/ElonMusk.lua",
		"Code/Stories/General/ElPresidente.lua",
		"Code/Stories/General/Equality.lua",
		"Code/Stories/General/Finances.lua",
		"Code/Stories/General/MarathonExplorer.lua",
		"Code/Stories/General/MarsDay.lua",
		"Code/Stories/General/MartianFaith.lua",
		"Code/Stories/General/MartianMusic.lua",
		"Code/Stories/General/MovingDomes.lua",
		"Code/Stories/General/NewLanguage.lua",
		"Code/Stories/General/Passport.lua",
		"Code/Stories/General/Rockets.lua",
		"Code/Stories/General/Vigilante.lua",
		"Code/Stories/LifeSupport/AirSupply.lua",
		"Code/Stories/LifeSupport/FoodShortage.lua",
		"Code/Stories/LifeSupport/PowerSupply.lua",
		"Code/Stories/LifeSupport/Shortages.lua",
		"Code/Stories/LifeSupport/WaterSupply.lua",
		"Code/Stories/Research/AdaptedProbes.lua",
		"Code/Stories/Research/CompactPassengerModule.lua",
		"Code/Stories/Research/DecommissionProtocol.lua",
		"Code/Stories/Research/DeepScanning.lua",
		"Code/Stories/Research/FuelCompression.lua",
		"Code/Stories/Research/HygroscopicVaporators.lua",
		"Code/Stories/Research/LiveFromMars.lua",
		"Code/Stories/Research/LowGFungi.lua",
		"Code/Stories/Research/LowGHydrosynthsis.lua",
		"Code/Stories/Research/LowGTurbines.lua",
		"Code/Stories/Research/MagneticFiltering.lua",
		"Code/Stories/Research/SoilAdaptation.lua",
		"Code/Stories/Research/SoylentGreen.lua",
		"Code/Stories/Research/SubsurfaceHeating.lua",
		"Code/Stories/Research/WaterReclamation.lua"
	},
	'loctables', {
		{
			filename = "Locales/English.csv",
			language = "English",
		},
	},
	'saved', 1534655233,
	'TagTranslations', true,
	'TagCosmetics', true,
	'TagOther', true,
})