return PlaceObj('ModDef', {
	'title', "The Martian Tribune",
	'image', "Martian Tribune Preview Picture.png",
	'last_changes', "fixed filepaths and notification icon",
	'id', "lf1iELO",
	'steam_id', "1376913896",
	'author', "CheTranqui",
	'version', 783,
	'lua_revision', 233467,
	'code', {
		"Code/1_SetStoryKeys.lua",
		"Code/2_SetMissingPublishedDay.lua",
		"Code/3_FixStoryChains.lua",
		"Code/4_FixDomeDelayColonist.lua",
		"Code/5_UpdateGlobals.lua",
		"Code/AdaptedProbes.lua",
		"Code/AdultFilm.lua",
		"Code/AirSupply.lua",
		"Code/Arcology.lua",
		"Code/Common.lua",
		"Code/CompactPassengerModule.lua",
		"Code/ConcreteLove.lua",
		"Code/ConcretePaving.lua",
		"Code/CookingFire.lua",
		"Code/DecommissionProtocol.lua",
		"Code/DeepScanning.lua",
		"Code/Diner.lua",
		"Code/Dome.lua",
		"Code/DomeBirthControl.lua",
		"Code/DomeOval.lua",
		"Code/DroneBreakdown.lua",
		"Code/DroneGoesViral.lua",
		"Code/DroneHack.lua",
		"Code/DroneRights.lua",
		"Code/DroneShortage.lua",
		"Code/EarthMarsInitiative.lua",
		"Code/EarthTourism.lua",
		"Code/EarthlingDomeDelay.lua",
		"Code/EarthsickColonist.lua",
		"Code/ElPresidente.lua",
		"Code/ElonMusk.lua",
		"Code/EngArchive.lua",
		"Code/EngPage.lua",
		"Code/Equality.lua",
		"Code/FightClub.lua",
		"Code/Finances.lua",
		"Code/FirstFounderDied.lua",
		"Code/FirstMartianbornDied.lua",
		"Code/FoodShortage.lua",
		"Code/FoundersFirstWords.lua",
		"Code/FoundersLegacy.lua",
		"Code/FrontPage.lua",
		"Code/FuelCompression.lua",
		"Code/FutureExpansion.lua",
		"Code/GuruGarden.lua",
		"Code/HappyBirthday.lua",
		"Code/Hippie.lua",
		"Code/HygroscopicVaporators.lua",
		"Code/IdiotFML.lua",
		"Code/Infirmary.lua",
		"Code/InitialStoryLists.lua",
		"Code/Initialization.lua",
		"Code/LeaderDied.lua",
		"Code/LiveFromMars.lua",
		"Code/LowGFungi.lua",
		"Code/LowGHydrosynthsis.lua",
		"Code/LowGTurbines.lua",
		"Code/MDSLaser.lua",
		"Code/MagneticFiltering.lua",
		"Code/MarathonExplorer.lua",
		"Code/MarsDay.lua",
		"Code/MartianCelebrity.lua",
		"Code/MartianFaith.lua",
		"Code/MartianFashion.lua",
		"Code/MartianMusic.lua",
		"Code/MartianTribune.lua",
		"Code/MartianTribuneSaveGameFixes.lua",
		"Code/MartianUniversity.lua",
		"Code/MovingDomes.lua",
		"Code/Moxie.lua",
		"Code/NewLanguage.lua",
		"Code/NewLeader.lua",
		"Code/NoFood.lua",
		"Code/NoPowerRave.lua",
		"Code/Notification.lua",
		"Code/OopsIBrokeItAgain.lua",
		"Code/OpenAirGym.lua",
		"Code/Passport.lua",
		"Code/PetRock.lua",
		"Code/PowerSupply.lua",
		"Code/PreciousMetalsExtractor.lua",
		"Code/ProductivityTraining.lua",
		"Code/ReligiousArtifact.lua",
		"Code/Rockets.lua",
		"Code/Shortages.lua",
		"Code/ShuttleHub.lua",
		"Code/SocialArchive.lua",
		"Code/SocialPage.lua",
		"Code/SoilAdaptation.lua",
		"Code/SoylentGreen.lua",
		"Code/Spacebar.lua",
		"Code/StarvingColonist.lua",
		"Code/Stories_Colonist_Whiner.lua",
		"Code/SubsurfaceHeating.lua",
		"Code/TopArchive.lua",
		"Code/Tunnel.lua",
		"Code/Upgrade.lua",
		"Code/Upgrade775to776.lua",
		"Code/Vegan.lua",
		"Code/Vigilante.lua",
		"Code/VirtueOverVices.lua",
		"Code/WaterReclamation.lua",
		"Code/WaterSupply.lua",
		"Code/Weekends.lua",
	},
	'loctables', {
		{
			filename = "Locales/English.csv",
			language = "English",
		},
	},
	'saved', 1535892422,
	'TagMissionSponsors', true,
	'TagGameplay', true,
	'TagResearch', true,
	'TagTranslations', true,
	'TagCosmetics', true,
	'TagInterface', true,
	'TagOther', true,
})