return PlaceObj('ModDef', {
	'title', "The Martian Tribune",
	'image', "Martian Tribune Preview Picture.png",
	'last_changes', "Stories now have relevant in-game images associated and shown when applicable!",
	'id', "lf1iELO",
	'steam_id', "1376913896",
	'author', "CheTranqui",
	'version', 788,
	'lua_revision', 237920,
	'code', {
		"Code/1_Initialization.lua",
		"Code/2_MartianTribune.lua",
		"Code/3_MartianTribuneSaveGameFixes.lua",
		"Code/SaveGameFixes_775_FixDomeDelayColonist.lua",
		"Code/SaveGameFixes_775_FixStoryChains.lua",
		"Code/SaveGameFixes_775_SetMissingPublishedDay.lua",
		"Code/SaveGameFixes_775_SetStoryKeys.lua",
		"Code/SaveGameFixes_775_UpdateGlobals.lua",
		"Code/SaveGameFixes_775_Upgrade.lua",
		"Code/SaveGameFixes_776_Upgrade.lua",
		"Code/SaveGameFixes_787_Upgrade.lua",
		"Code/Stories_Building_Arcology.lua",
		"Code/Stories_Building_ConcreteLove.lua",
		"Code/Stories_Building_Diner.lua",
		"Code/Stories_Building_Dome.lua",
		"Code/Stories_Building_DomeOval.lua",
		"Code/Stories_Building_Infirmary.lua",
		"Code/Stories_Building_MartianUniversity.lua",
		"Code/Stories_Building_MDSLaser.lua",
		"Code/Stories_Building_Moxie.lua",
		"Code/Stories_Building_OpenAirGym.lua",
		"Code/Stories_Building_PreciousMetalsExtractor.lua",
		"Code/Stories_Building_ShuttleHub.lua",
		"Code/Stories_Building_Spacebar.lua",
		"Code/Stories_Building_Tunnel.lua",
		"Code/Stories_Colonist_AdultFilm.lua",
		"Code/Stories_Colonist_ConcretePaving.lua",
		"Code/Stories_Colonist_DroneHack.lua",
		"Code/Stories_Colonist_DroneRights.lua",
		"Code/Stories_Colonist_EarthlingDomeDelay.lua",
		"Code/Stories_Colonist_EarthsickColonist.lua",
		"Code/Stories_Colonist_EarthTourism.lua",
		"Code/Stories_Colonist_FightClub.lua",
		"Code/Stories_Colonist_FirstFounderDied.lua",
		"Code/Stories_Colonist_FirstMartianbornDied.lua",
		"Code/Stories_Colonist_FoundersFirstWords.lua",
		"Code/Stories_Colonist_FoundersLegacy.lua",
		"Code/Stories_Colonist_GuruGarden.lua",
		"Code/Stories_Colonist_HappyBirthday.lua",
		"Code/Stories_Colonist_Hippie.lua",
		"Code/Stories_Colonist_IdiotFML.lua",
		"Code/Stories_Colonist_LeaderDied.lua",
		"Code/Stories_Colonist_MartianCelebrity.lua",
		"Code/Stories_Colonist_MartianFashion.lua",
		"Code/Stories_Colonist_MovingDomes.lua",
		"Code/Stories_Colonist_NewLeader.lua",
		"Code/Stories_Colonist_OopsIBrokeItAgain.lua",
		"Code/Stories_Colonist_PetRock.lua",
		"Code/Stories_Colonist_ReligiousArtifact.lua",
		"Code/Stories_Colonist_StarvingColonist.lua",
		"Code/Stories_Colonist_Vegan.lua",
		"Code/Stories_Colonist_VirtueOverVices.lua",
		"Code/Stories_Colonist_Whiner.lua",
		"Code/Stories_Drone_DroneBreakdown.lua",
		"Code/Stories_Drone_DroneGoesViral.lua",
		"Code/Stories_Drone_DroneShortage.lua",
		"Code/Stories_General_Aging.lua",
		"Code/Stories_General_Aurorae.lua",
		"Code/Stories_General_CookingFire.lua",
		"Code/Stories_General_DomeBirthControl.lua",
		"Code/Stories_General_DustStorms.lua",
		"Code/Stories_General_ElonMusk.lua",
		"Code/Stories_General_ElPresidente.lua",
		"Code/Stories_General_Equality.lua",
		"Code/Stories_General_Finances.lua",
		"Code/Stories_General_FirstColonistsLeaveEarth.lua",
		"Code/Stories_General_FutureExpansion.lua",
		"Code/Stories_General_MarathonExplorer.lua",
		"Code/Stories_General_MarsDay.lua",
		"Code/Stories_General_MartianFaith.lua",
		"Code/Stories_General_MartianMusic.lua",
		"Code/Stories_General_MeteorStorm.lua",
		"Code/Stories_General_NewLanguage.lua",
		"Code/Stories_General_Passport.lua",
		"Code/Stories_General_Rockets.lua",
		"Code/Stories_General_Vigilante.lua",
		"Code/Stories_General_Weekends.lua",
		"Code/Stories_InitialStoryLists.lua",
		"Code/Stories_LifeSupport_AirSupply.lua",
		"Code/Stories_LifeSupport_FoodShortage.lua",
		"Code/Stories_LifeSupport_NoFood.lua",
		"Code/Stories_LifeSupport_NoPowerRave.lua",
		"Code/Stories_LifeSupport_PowerSupply.lua",
		"Code/Stories_LifeSupport_Shortages.lua",
		"Code/Stories_LifeSupport_WaterSupply.lua",
		"Code/Stories_Research_AdaptedProbes.lua",
		"Code/Stories_Research_CompactPassengerModule.lua",
		"Code/Stories_Research_DecommissionProtocol.lua",
		"Code/Stories_Research_DeepScanning.lua",
		"Code/Stories_Research_EarthMarsInitiative.lua",
		"Code/Stories_Research_FuelCompression.lua",
		"Code/Stories_Research_HygroscopicVaporators.lua",
		"Code/Stories_Research_LiveFromMars.lua",
		"Code/Stories_Research_LowGFungi.lua",
		"Code/Stories_Research_LowGHydrosynthsis.lua",
		"Code/Stories_Research_LowGTurbines.lua",
		"Code/Stories_Research_MagneticFiltering.lua",
		"Code/Stories_Research_ProductivityTraining.lua",
		"Code/Stories_Research_SoilAdaptation.lua",
		"Code/Stories_Research_SoylentGreen.lua",
		"Code/Stories_Research_SubsurfaceHeating.lua",
		"Code/Stories_Research_WaterReclamation.lua",
		"Code/UI_Common.lua",
		"Code/UI_EngArchive.lua",
		"Code/UI_EngPage.lua",
		"Code/UI_FrontPage.lua",
		"Code/UI_Notification.lua",
		"Code/UI_SocialArchive.lua",
		"Code/UI_SocialPage.lua",
		"Code/UI_TopArchive.lua",
	},
	'loctables', {
		{
			filename = "Locales/English.csv",
			language = "English",
		},
	},
	'saved', 1543002394,
	'TagMissionSponsors', true,
	'TagGameplay', true,
	'TagResearch', true,
	'TagTranslations', true,
	'TagCosmetics', true,
	'TagInterface', true,
	'TagOther', true,
})